name: CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hoster
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
