name: CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Move files to html root
        run: rsync /home/actions/actions-runner/_work/ullavs.nl/ullavs.nl/ /var/www/ullavs.nl/html/ -va --exclude .git --exclude .github
